# Generated by Django 4.2.13 on 2024-11-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado'), ('examen', 'Examen'), ('plazo', 'Plazo Administrativo')], max_length=50)),
            ],
        ),
    ]
