# Generated by Django 4.2.13 on 2024-11-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha_fin',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fecha_inicio',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='titulo',
            new_name='title',
        ),
    ]
